package model;

public class Student {

    // Fields
    private int    id;
    private String firstName;
    private String lastName;
    private int    age;
    private double grade;

    // Constructor (with ID)
    // Full constructor — used when retrieving a student from the database (the ID is already known)
    
    public Student(int id, String firstName, String lastName, int age, double grade) {
        this.id        = id;
        this.firstName = firstName;
        this.lastName  = lastName;
        this.age       = age;
        this.grade     = grade;
    }

    // Constructor (without ID)
    // Constructor without ID — used when creating a new student before saving 
    // to the database (the ID is auto-generated by PostgreSQL via SERIAL)
    
    public Student(String firstName, String lastName, int age, double grade) {
        this.firstName = firstName;
        this.lastName  = lastName;
        this.age       = age;
        this.grade     = grade;
    }

    // Getters

    public int getId() {
        return id;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public int getAge() {
        return age;
    }

    public double getGrade() {
        return grade;
    }

    // Setters

    public void setId(int id) {
        this.id = id;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public void setGrade(double grade) {
        this.grade = grade;
    }

    // Utility methods
    // Returns the student's full name (first name + last name)
     
    public String getFullName() {
        return firstName + " " + lastName;
    }

    // Checks whether the student is passing (grade >= 10.0 out of 20)
    //return true if the student passes, false otherwise
     
    public boolean isPassing() {
        return grade >= 10.0;
    }

    // Returns a formatted string representation of the student
    // Useful for debugging and console output
     
    @Override
    public String toString() {
        return String.format(
            "Student { id=%d | name=%s %s | age=%d | grade=%.2f | status=%s }",
            id,
            firstName,
            lastName,
            age,
            grade,
            isPassing() ? "PASS" : "FAIL"
        );
    }

    // Two students are equal if they share the same ID
    //return true if the students are equal, false otherwise

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!(obj instanceof Student)) return false;
        Student other = (Student) obj;
        return this.id == other.id;
    }

    @Override
    public int hashCode() {
        return Integer.hashCode(id);
    }
}